name: Release
on:
  push:
    tags:
      - '*.*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to github
    steps:
      - uses: actions/checkout@v2
      - name: Set release version environment variable
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up JDK 1.17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Cache maven
        uses: actions/cache@v2.1.3
        with:
          path: ~/.m2/repository
          key: maven_cache
      - name: Gradle build
        env:
          BUILD_ENV: 'github-actions'
        run: ./gradlew buildPlugin
      - name: Create github release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: 'TODO'
          draft: false
          prerelease: false
      - name: Upload zip to github release
        id: upload-release-asset-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/build/distributions/chutney-idea-plugin-${{ env.RELEASE_VERSION }}.zip
          asset_name: chutney-idea-plugin-${{ env.RELEASE_VERSION }}.zip
          asset_content_type: application/zip
