#SPDX-FileCopyrightText: 2017-2024 Enedis
#SPDX-License-Identifier: Apache-2.0

blank_issues_enabled: false
contact_links:
  - name: ðŸ™‹ Ask Questions, Get Help and Share ideas ðŸ’¡
    url: https://github.com/chutney-testing/chutney/discussions
    about: A place to get help, Q&A, new ideas and discussions
  - name: ðŸ’¬ Live chat and private messages
    url: https://chutney-testing.zulipchat.com/
    about: A more informal place to get in touch if you need it
  - name: ðŸŒ‹ Security / Vulnerabilities
    url: https://chutney-testing.zulipchat.com/
    about: Please get in touch with us using private messages on our Zulip server
