#SPDX-FileCopyrightText: 2017-2024 Enedis
#SPDX-License-Identifier: Apache-2.0

chutney:
  db-server:
    base-dir: ./.chutney/data

spring:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.community.dialect.SQLiteDialect
      hibernate.id.new_generator_mappings: false
  datasource:
    url: jdbc:sqlite:${chutney.db-server.base-dir}/sqlitesample.db
