name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: Deploy to central
    steps:
      - uses: actions/checkout@v2

      - name: Set release version environment variable
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Verify the project build
        run: ./gradlew clean build

      - name: Publish to OSSRH
        run: ./gradlew publish
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          CHUTNEY_GPG_KEY_ID: ${{ secrets.CHUTNEY_GPG_KEY_ID }}
          CHUTNEY_GPG_KEY: ${{ secrets.CHUTNEY_GPG_PRIVATE_KEY }}
          CHUTNEY_GPG_PASSPHRASE: ${{ secrets.CHUTNEY_GPG_PASSPHRASE }}

      - name: Create github release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: 'TODO'
          draft: false
          prerelease: false

      - name: Upload jar to github release
        id: upload-release-asset-dsl-jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/dsl/build/libs/chutney-kotlin-dsl-${{ env.RELEASE_VERSION }}.jar
          asset_name: chutney-kotlin-dsl-${{ env.RELEASE_VERSION }}.jar
          asset_content_type: application/jar

      - name: Upload signature to github release
        id: upload-release-asset-dsl-jar-sig
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/dsl/build/libs/chutney-kotlin-dsl-${{ env.RELEASE_VERSION }}.jar.asc
          asset_name: chutney-kotlin-dsl-${{ env.RELEASE_VERSION }}.jar.asc
          asset_content_type: application/pgp-signature
